# NumPy Basics: Arrays and Vectorized Computation

In [1]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

## The NumPy ndarray: A Multidimensional Array Object

In [8]:
import numpy as np
# Generate some random data
data = np.random.randn(2, 3)
data

array([[ 1.06391183,  1.43657615,  0.09288337],
       [-0.52007358,  1.39595351, -0.00563458]])

In [9]:
data.mean()

0.5772694508650547

In [10]:
data_1 = np.random.randn(10000)

In [11]:
data_1.mean()

-0.008011834864406892

In [12]:
data * 10

array([[10.63911829, 14.36576154,  0.92883366],
       [-5.20073576, 13.95953509, -0.05634576]])

In [13]:
data + data

array([[ 2.12782366,  2.87315231,  0.18576673],
       [-1.04014715,  2.79190702, -0.01126915]])

In [5]:
data.shape

(2, 3)

In [70]:
data.dtype

dtype('float64')

### Creating ndarrays

In [14]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [16]:
data11 = [6, 7, 8, 0, 1]
arr11 = np.array(data11)
arr11

array([6, 7, 8, 0, 1])

In [17]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr2.ndim

2

In [19]:
arr2.shape

(2, 4)

In [10]:
arr1.dtype

dtype('float64')

In [11]:
arr2.dtype

dtype('int32')

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [22]:
np.empty((2, 3))

array([[2.12782366, 2.87315231, 0.18576673],
       [1.04014715, 2.79190702, 0.01126915]])

In [20]:
np.empty((2, 3, 2))

array([[[1.01855798e-312, 1.08221785e-312],
        [1.01855798e-312, 9.54898106e-313],
        [1.16709769e-312, 1.01855798e-312]],

       [[1.23075756e-312, 1.08221785e-312],
        [1.01855798e-312, 9.76118064e-313],
        [1.20953760e-312, 1.90979621e-312]]])

In [16]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays

In [23]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [24]:
arr1.dtype

dtype('float64')

In [25]:
arr2.dtype

dtype('int32')

In [26]:
float_arr = arr2.astype(np.float64)
float_arr.dtype

dtype('float64')

In [27]:
float_arr

array([1., 2., 3.])

In [31]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [34]:
numeric_strings = np.array([1.25, -9.6, 42], dtype=np.string_)
numeric_strings_2=numeric_strings.astype(float)

In [35]:
numeric_strings_2

array([ 1.25, -9.6 , 42.  ])

In [36]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### Arithmetic with NumPy Arrays

In [37]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [38]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [31]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [39]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [34]:
arr


array([[1., 2., 3.],
       [4., 5., 6.]])

In [41]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [36]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### Basic Indexing and Slicing

In [42]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arr[0]

0

In [44]:
arr[5]

5

In [45]:
arr[5:8]

array([5, 6, 7])

In [46]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [47]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [48]:
arr_slice[2] = 12345
arr

array([    0,     1,     2,     3,     4,    12,    12, 12345,     8,
           9])

In [44]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [49]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
arr2d[0]

array([1, 2, 3])

In [51]:
arr2d[1]

array([4, 5, 6])

In [52]:
arr2d[2]

array([7, 8, 9])

In [49]:
arr2d[0][2]

3

In [53]:
arr2d[0,2]

3

In [55]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [56]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
arr3d[0][0]

array([1, 2, 3])

In [59]:
arr3d[0][1]

array([4, 5, 6])

In [57]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [54]:
arr3d[0][1]

array([4, 5, 6])

In [60]:
arr3d[0][1][2]

6

In [56]:
arr3d[1][0][1]

8

In [59]:
arr3d[1][0]

array([7, 8, 9])

In [60]:
arr3d[1, 0]

array([7, 8, 9])

In [61]:
arr3d[1,0,2]

9

In [62]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [63]:
x[0]

array([7, 8, 9])

In [64]:
x[0][1]

8

#### Indexing with slices

In [65]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [66]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [67]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [70]:
arr2d[1, :2]

array([4, 5])

In [71]:
arr2d[:2, 2]

array([3, 6])

In [72]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [73]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Boolean Indexing

In [74]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [75]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [76]:
names1 = np.array(['Bob', 'Joe', 'Will', 'Bob'])

In [77]:
data = np.random.randn(7, 4)

In [78]:
data

array([[ 0.0929,  0.2817,  0.769 ,  1.2464],
       [ 1.0072, -1.2962,  0.275 ,  0.2289],
       [ 1.3529,  0.8864, -2.0016, -0.3718],
       [ 1.669 , -0.4386, -0.5397,  0.477 ],
       [ 3.2489, -1.0212, -0.5771,  0.1241],
       [ 0.3026,  0.5238,  0.0009,  1.3438],
       [-0.7135, -0.8312, -2.3702, -1.8608]])

In [79]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [80]:
data[names == 'Bob']

array([[ 0.0929,  0.2817,  0.769 ,  1.2464],
       [ 1.669 , -0.4386, -0.5397,  0.477 ]])

In [81]:
data[names == 'Bob', 2:]

array([[ 0.769 ,  1.2464],
       [-0.5397,  0.477 ]])

In [82]:
data[names == 'Bob', 3]

array([1.2464, 0.477 ])

In [83]:
data[2, names1=='Bob']

array([ 1.3529, -0.3718])

In [84]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [85]:
data[~(names == 'Bob')]

array([[ 1.0072, -1.2962,  0.275 ,  0.2289],
       [ 1.3529,  0.8864, -2.0016, -0.3718],
       [ 3.2489, -1.0212, -0.5771,  0.1241],
       [ 0.3026,  0.5238,  0.0009,  1.3438],
       [-0.7135, -0.8312, -2.3702, -1.8608]])

### Transposing Arrays and Swapping Axes

In [86]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [87]:
arr_T=arr.T

In [88]:
arr_T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [89]:
a = [[1, 2], [4, 1]]  
b = [[4, 11], [2, 3]]  
c=np.dot(a, b)  # matrix multiplication
c  

array([[ 8, 17],
       [18, 47]])

In [90]:
c=np.dot(b, a)
c

array([[48, 19],
       [14,  7]])

In [91]:
arr = np.random.randn(6, 3)
arr

array([[-0.8608,  0.5601, -1.2659],
       [ 0.1198, -1.0635,  0.3329],
       [-2.3594, -0.1995, -1.542 ],
       [-0.9707, -1.307 ,  0.2863],
       [ 0.378 , -0.7539,  0.3313],
       [ 1.3497,  0.0699,  0.2467]])

In [92]:
arr.T

array([[-0.8608,  0.1198, -2.3594, -0.9707,  0.378 ,  1.3497],
       [ 0.5601, -1.0635, -0.1995, -1.307 , -0.7539,  0.0699],
       [-1.2659,  0.3329, -1.542 ,  0.2863,  0.3313,  0.2467]])

In [93]:
np.dot(arr.T, arr)

array([[ 9.2291,  0.9394,  4.948 ],
       [ 0.9394,  3.7662, -1.3622],
       [ 4.948 , -1.3622,  4.3437]])

In [94]:
np.dot(arr, arr.T)

array([[ 2.6573, -1.1203,  3.8712, -0.2591, -1.167 , -1.4349],
       [-1.1203,  1.2562, -0.5838,  1.369 ,  0.9573,  0.1695],
       [ 3.8712, -0.5838,  7.9844,  2.1096, -1.2522, -3.5789],
       [-0.2591,  1.369 ,  2.1096,  2.7327,  0.7133, -1.3309],
       [-1.167 ,  0.9573, -1.2522,  0.7133,  0.821 ,  0.5392],
       [-1.4349,  0.1695, -3.5789, -1.3309,  0.5392,  1.8875]])

In [95]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [96]:
arr.strides

(32, 16, 4)

In [97]:
arr.transpose((1, 0, 2))  # [0, 1] interchanged with [1, 0]

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [98]:
arr.transpose((1, 0, 2)).strides

(16, 32, 4)

In [99]:
arr  # the array remains unchanged. Swapping axess is not in-place

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [100]:
arr.strides

(32, 16, 4)

In [101]:
arr.transpose(2,1,0) 

# Initial array shape (2,2,4). Swapping axes 0 and 2 will reshape it into
# (4,2,2)

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [102]:
arr.transpose(2,1,0).strides

(4, 16, 32)

In [103]:
arr
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## Universal Functions: Fast Element-Wise Array Functions

In [104]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
np.sqrt(arr)

array([0.    , 1.    , 1.4142, 1.7321, 2.    , 2.2361, 2.4495, 2.6458,
       2.8284, 3.    ])

In [106]:
np.exp(arr)

array([   1.    ,    2.7183,    7.3891,   20.0855,   54.5982,  148.4132,
        403.4288, 1096.6332, 2980.958 , 8103.0839])

In [107]:
x = np.random.randn(8)
y = np.random.randn(8)

In [108]:
x

array([-0.0119,  1.0048,  1.3272, -0.9193, -1.5491,  0.0222,  0.7584,
       -0.6605])

In [109]:
y

array([ 0.8626, -0.01  ,  0.05  ,  0.6702,  0.853 , -0.9559, -0.0235,
       -2.3042])

In [110]:
np.maximum(x, y)

array([ 0.8626,  1.0048,  1.3272,  0.6702,  0.853 ,  0.0222,  0.7584,
       -0.6605])

In [111]:
arr = np.random.randn(7) * 5
arr

array([-3.2623, -6.0915, -6.663 ,  5.3731,  3.6182,  3.45  ,  5.0077])

In [112]:
fractional_part, whole_part = np.modf(arr)

In [113]:
fractional_part

array([-0.2623, -0.0915, -0.663 ,  0.3731,  0.6182,  0.45  ,  0.0077])

In [114]:
whole_part

array([-3., -6., -6.,  5.,  3.,  3.,  5.])

### Mathematical and Statistical Methods

In [115]:
arr = np.random.randn(5, 4)
arr

array([[-0.5031, -0.6223, -0.9212, -0.7262],
       [ 0.2229,  0.0513, -1.1577,  0.8167],
       [ 0.4336,  1.0107,  1.8249, -0.9975],
       [ 0.8506, -0.1316,  0.9124,  0.1882],
       [ 2.1695, -0.1149,  2.0037,  0.0296]])

In [116]:
arr.mean()

0.26698189961874014

In [117]:
np.mean(arr)

0.26698189961874014

In [118]:
arr.sum()

5.3396379923748025

In [119]:
np.sum(arr)

5.3396379923748025

In [120]:
np.std(arr)

0.9625311453645782

In [121]:
arr.mean(axis=1)  # row-wise sum

array([-0.6932, -0.0167,  0.5679,  0.4549,  1.022 ])

In [122]:
arr.sum(axis=0)  # column-wise sum

array([ 3.1735,  0.1933,  2.6621, -0.6892])

In [123]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [124]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [125]:
arr.cumsum(axis=0)   # column-wise

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [126]:
arr.cumprod(axis=1)  # row-wise

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

### Methods for Boolean Arrays

In [127]:
arr = np.random.randn(100)
arr

array([ 0.7953,  0.1181, -0.7485,  0.585 ,  0.1527, -1.5657, -0.5625,
       -0.0327, -0.929 , -0.4826, -0.0363,  1.0954,  0.9809, -0.5895,
        1.5817, -0.5287,  0.457 ,  0.93  , -1.5693, -1.0225, -0.4028,
        0.2205, -0.1934,  0.6692, -1.649 , -2.2528, -1.1668,  0.3536,
        0.7021, -0.2746, -0.1391,  0.1077, -0.6065, -0.4171, -0.017 ,
       -1.2241, -1.8008,  1.6347,  0.989 ,  0.4579,  0.5552,  1.3067,
       -0.4406, -0.3014,  0.4988, -0.824 ,  1.3206,  0.508 , -0.6534,
        0.187 , -0.3917, -0.2723, -0.0171,  0.6803,  0.6355, -0.7572,
        0.7181, -0.3043, -1.6778,  0.427 , -1.5637, -0.3675,  1.0459,
        1.22  , -0.2477, -0.4162, -0.1167, -1.8448,  2.0687, -0.777 ,
        1.4402, -0.1106,  1.2274,  1.9208,  0.7464,  2.2247, -0.6794,
        0.7274, -0.8687, -1.2139, -0.4706, -0.9192, -0.8388,  0.4352,
       -0.5578, -0.5675, -0.3726, -0.9266,  1.7551,  1.2098,  1.27  ,
       -0.9744, -0.6347, -0.3957, -0.2894, -0.7343, -0.7285,  0.8388,
        0.2669,  0.7

In [128]:
(arr > 0).sum() # Number of positive values

43

In [129]:
bools = np.array([False, False, True, False])

In [130]:
bools.any()

True

In [131]:
bools.all()

False

### Sorting

In [132]:
arr = np.random.randn(6)
arr

array([ 0.911 , -1.0209, -1.4134,  1.2966,  0.2523,  1.1275])

In [133]:
arr.sort()

In [134]:
arr

array([-1.4134, -1.0209,  0.2523,  0.911 ,  1.1275,  1.2966])

In [135]:
arr = np.random.randn(5, 3)
arr

array([[-0.5684,  0.3094, -0.5774],
       [-1.1686, -0.825 , -2.6444],
       [-0.153 , -0.7519, -0.1326],
       [ 1.4573,  0.6095, -0.4938],
       [ 1.24  , -0.1357,  1.43  ]])

In [136]:
arr.sort(1) #in-place column-wise sorting

In [137]:
arr

array([[-0.5774, -0.5684,  0.3094],
       [-2.6444, -1.1686, -0.825 ],
       [-0.7519, -0.153 , -0.1326],
       [-0.4938,  0.6095,  1.4573],
       [-0.1357,  1.24  ,  1.43  ]])

In [138]:
arr = np.random.randn(5, 3)
arr

array([[-0.8469,  0.6033,  1.2636],
       [-0.2555, -0.4457,  0.4684],
       [-0.9616, -1.8245,  0.6254],
       [ 1.0229,  1.1074,  0.0909],
       [-0.3501,  0.218 , -0.8948]])

In [139]:
arr.sort()

In [140]:
arr

array([[-0.8469,  0.6033,  1.2636],
       [-0.4457, -0.2555,  0.4684],
       [-1.8245, -0.9616,  0.6254],
       [ 0.0909,  1.0229,  1.1074],
       [-0.8948, -0.3501,  0.218 ]])

In [141]:
arr.sort(0)
arr

array([[-1.8245, -0.9616,  0.218 ],
       [-0.8948, -0.3501,  0.4684],
       [-0.8469, -0.2555,  0.6254],
       [-0.4457,  0.6033,  1.1074],
       [ 0.0909,  1.0229,  1.2636]])

In [142]:
large_arr = np.random.randn(1000)
large_arr.sort()

In [143]:
large_arr[int(0.05 * len(large_arr))] # 5% quantile

-1.551714991950571

In [144]:
large_arr[int(0.5 * len(large_arr))] # 5% quantile

-0.055100992927449126

### Unique and Other Set Logic

In [145]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [146]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

In [147]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [148]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

## File Input and Output with Arrays

In [149]:
arr = np.arange(10)
np.save('some_array', arr)

In [150]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [151]:
np.savez('array_archive.npz', a=arr, b=arr)

In [152]:
arch = np.load('array_archive.npz')
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [153]:
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [154]:
np.savez_compressed('array_archive.npz', a=arr, b=arr)

## Linear Algebra

In [155]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [156]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [157]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [158]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [159]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [160]:
np.dot(y, x)

array([[ 98., 127., 156.],
       [ 27.,  33.,  39.],
       [ 44.,  61.,  78.]])

In [161]:
np.ones(3)

array([1., 1., 1.])

In [162]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [163]:
np.dot(x, np.ones(3)) #does not follow mathematical rule of matrix multiplication

array([ 6., 15.])

In [164]:
x @ np.ones(3) # a special operation for numpy matrices 

array([ 6., 15.])

In [165]:
from numpy.linalg import inv, qr
X = np.random.randn(5, 5)

In [166]:
X

array([[ 1.2136, -0.638 , -0.3739, -0.0534, -0.1046],
       [ 0.3938, -0.132 , -0.5292,  0.3035, -0.8896],
       [-0.1733,  0.6433, -1.254 ,  0.1172,  0.8665],
       [ 1.0795, -0.3975,  1.4875,  0.558 ,  0.6144],
       [ 0.428 , -0.272 ,  0.7388, -0.5081,  1.3153]])

In [167]:
X.T

array([[ 1.2136,  0.3938, -0.1733,  1.0795,  0.428 ],
       [-0.638 , -0.132 ,  0.6433, -0.3975, -0.272 ],
       [-0.3739, -0.5292, -1.254 ,  1.4875,  0.7388],
       [-0.0534,  0.3035,  0.1172,  0.558 , -0.5081],
       [-0.1046, -0.8896,  0.8665,  0.6144,  1.3153]])

In [168]:
mat = X.T.dot(X)

In [169]:
mat

array([[ 3.0063, -1.4833,  1.477 ,  0.4193,  0.5986],
       [-1.4833,  1.0703, -1.2904, -0.0142,  0.1398],
       [ 1.477 , -1.2904,  4.7509,  0.167 ,  1.3088],
       [ 0.4193, -0.0142,  0.167 ,  0.6783, -0.4883],
       [ 0.5986,  0.1398,  1.3088, -0.4883,  3.6606]])

In [170]:
mat1= X.dot(X.T)

In [171]:
mat1

array([[ 2.0335,  0.8369, -0.2488,  0.9133,  0.3062],
       [ 0.8369,  1.3362, -0.2248, -0.6868, -1.5108],
       [-0.2488, -0.2248,  2.7811, -1.7104, -0.0954],
       [ 0.9133, -0.6868, -1.7104,  4.2247,  2.1935],
       [ 0.3062, -1.5108, -0.0954,  2.1935,  2.791 ]])

In [172]:
inv(mat)

array([[ 100.9816,  191.9216,   38.6697, -105.1463,  -51.6909],
       [ 191.9216,  366.3603,   74.0196, -200.1413,  -98.5314],
       [  38.6697,   74.0196,   15.2249,  -40.5005,  -19.995 ],
       [-105.1463, -200.1413,  -40.5005,  111.2475,   54.1542],
       [ -51.6909,  -98.5314,  -19.995 ,   54.1542,   26.8599]])

In [173]:
inv(mat1)

array([[  87.4561, -180.9745,   -4.9228,    9.4841, -115.1845],
       [-180.9745,  376.8944,   10.1152,  -20.153 ,  240.0648],
       [  -4.9228,   10.1152,    0.8646,   -0.1353,    6.1517],
       [   9.4841,  -20.153 ,   -0.1353,    1.7946,  -13.365 ],
       [-115.1845,  240.0648,    6.1517,  -13.365 ,  153.6645]])

In [174]:
mat.dot(inv(mat))

array([[ 1., -0.,  0.,  0.,  0.],
       [ 0.,  1., -0., -0.,  0.],
       [-0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0., -0.,  0., -0.,  1.]])

In [175]:
q, r = qr(mat)

In [176]:
q

array([[-0.8048, -0.2787,  0.3326, -0.0372, -0.4032],
       [ 0.3971, -0.3046, -0.26  , -0.302 , -0.7686],
       [-0.3954,  0.5967, -0.663 , -0.1539, -0.156 ],
       [-0.1122, -0.2905, -0.0977, -0.8456,  0.4224],
       [-0.1602, -0.6238, -0.6104,  0.4108,  0.2095]])

In [177]:
r

array([[-3.7355,  2.1082, -3.8081, -0.407 , -1.4755],
       [ 0.    , -0.7656,  1.9512,  0.0946, -1.57  ],
       [ 0.    ,  0.    , -3.1385,  0.2642, -2.8918],
       [ 0.    ,  0.    ,  0.    , -0.8111,  1.6507],
       [ 0.    ,  0.    ,  0.    ,  0.    ,  0.0078]])

## Pseudorandom Number Generation

In [178]:
samples1 = np.random.randn(4,4)
# Generates a standard normal distribution with mean by default 0 and sd by default 1 and they cannot be changed.
samples1

array([[ 0.4459,  0.5732,  0.1933,  0.4429],
       [ 1.2796,  0.575 ,  0.4339, -0.7658],
       [-1.237 , -0.5367,  1.8545, -0.92  ],
       [-0.1082,  0.1525,  0.9435, -1.0953]])

In [179]:
samples = np.random.normal(loc=6, scale = 1.25, size=(4, 4)) 
# Generates a set of data points following a general normal distribution with mean = loc, and sd = scale.  
# Default values of loc and scale are 9 and 1 respectively.
samples

array([[5.82  , 8.4453, 5.636 , 6.131 ],
       [6.1745, 5.6449, 5.1148, 9.079 ],
       [6.2718, 5.9868, 5.9924, 6.6126],
       [5.6535, 5.116 , 5.2999, 9.4194]])

In [180]:
samples = np.random.normal(size=(4, 4))
samples

array([[ 0.9273,  1.5139,  0.5386,  1.2738],
       [ 0.6679, -0.9692,  1.6761, -0.8176],
       [ 0.0502,  1.9513,  3.2604,  0.9633],
       [ 1.2012, -1.852 ,  2.4068,  0.8412]])

In [181]:
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0, 1) for _ in range(N)]
%timeit np.random.normal(size=N)

703 ms ± 8.47 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
22.8 ms ± 675 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [182]:
np.random.seed(1234)

In [183]:
rng = np.random.RandomState(1234)
rng.randn(10)

array([ 0.4714, -1.191 ,  1.4327, -0.3127, -0.7206,  0.8872,  0.8596,
       -0.6365,  0.0157, -2.2427])